services:
  fishtest-worker:
    container_name: fishtest-worker
    build:
      dockerfile: ./Dockerfile
    stop_grace_period: 30s
    shm_size: '1gb'  # for shared network before sf 19
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      options:
        max-size: 10m
    environment:
      - WORKER_ARGS
    networks:
      - default

networks:
  default:
    enable_ipv6: true
