services:
  fishtest-worker:
    build:
      dockerfile: ./Dockerfile
    stop_grace_period: 30s
    container_name: fishtest-worker
    shm_size: '1gb'  # for shared network
    environment:
      - WORKER_ARGS
